### ISSUE TITLE
AttributeError: module 'InvertedIndex3' has no attribute 'index_lookup_query'

### ISSUE THREAD

**Issue by WK-GiHu** [MTXIII/InvIndex-w-tkinter#5]
When running the gui file I'm getting:

> Exception in Tkinter callback
> Traceback (most recent call last):
> ...
> ...\gui2.py", line 15, in open
>     for line in bck.index_lookup_query(Term.get()):
> AttributeError: module 'InvertedIndex3' has no attribute 'index_lookup_query'

The `index_lookup_query` function is defined in the file so I'm unsure why the AttributeError is firing.

**Comment by WK-GiHu** [comment]
@MTXIII 

>The index_lookup_query function is defined in the file so I'm unsure why the AttributeError is firing.

Yes, can't find the reason for now.
It's bad practice to change the module name, here `'InvertedIndex3'`.
Copy `'InvertedIndex.py'` to `'InvertedIndex3.py'` if you want to backup, but **stay** and **edit** only the original `'InvertedIndex.py'`.
GitHub hold a **History** file by default.

Verify if you can access **any** from `'InvertedIndex.py`, e.g. `db = bck.Database()`
Do `print(bck)`, show the output.
Do `print(dir(bck))`, search if `index_lookup_query` is in the output.

**Comment by MTXIII** [comment]
Original filenames updated, thanks for pointing that out.

Access Verified:
> >>> import InvertedIndex as bck
>>> print(bck)
<module 'InvertedIndex' from 'C:\\..\\InvInd\\InvertedIndex.py'>

index__lookup_query verified too: 
> >>> print(dir(InvertedIndex))
> ['Appearance', 'Database', 'InvertedIndex', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'g', 'index_documents', 'index_lookup_query', 'main', 're']

**Comment by MTXIII** [comment]
@WK-GiHu 
So the program is functioning as planned for currently, but I'm a bit confused why simply moving the `index_lookup_query` function down to just before `main()` got rid of the AttributeError.

Do you have an idea of why?

**Comment by WK-GiHu** [comment]
@MTXIII 

>So the program is functioning as planned for currently, 

OK

>but I'm a bit confused why simply moving the index_lookup_query function down to just before main() got rid of the AttributeError.

The move was needed as you call `def index_documents`, which was defined beneath, but functions have to be defined before it can be used.

I don't think this solves the `AttributeError: module 'InvertedIndex3' has no attribute 'index_lookup_query'`. I assume you are confused by multiple renaming the file.

**Comment by MTXIII** [comment]
You are right, my mistake. 
I am still facing the `AttributeError` for `index_lookup_query` when running **gui.py**.

**Comment by WK-GiHu** [comment]
@MTXIII 

>I am still facing the `AttributeError` for `index_lookup_query` when running gui.py.

Your output is misleading, you use `print(dir(InvertedIndex))`, 
but  your statement is `bck.index_lookup_query`:

>                print(dir(InvertedIndex))
>                ['Appearance', 'Database', 'InvertedIndex', ... 'index_lookup_query', 'main', 're']

---

Repeat the check, and show the output with Traceback: 
```
   print(bck)
   print(dir(bck))
   for line in bck.index_lookup_query(Term.get()):
```

**Comment by MTXIII** [comment]
Ok. 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'bck' is not defined
> >>> print(dir(bck))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'bck' is not defined
> >>> for line in bck.index__lookup_query(Term.get()):
> ...                                                                                            

Looks like `bck` isn't being defined. Though when i run `gui.py` and enter a term the output from `InvertedIndex.py` is shown in the second window.

**Comment by MTXIII** [comment]
@WK-GiHu 
I have also tried changing the import from `import InvertedIndex as bck` to `from InvertedIndex import *` as to import the functions directly into the local namespace. The result of which is `NameError: name 'index_lookup_query' is not defined`.

Furthermore when i run:

```
>>> import gui
>>> len(globals())
8
>>> globals()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 'gui': <module 'gui' from 'C:\\Users\\MTXIII\\Documents\\Dev\\Python\\Projects\\InvIndex\\gui\\InvInd\\gui.py'>}
>>>        
```

nothing from InvertedIndex is imported. 
Am I correct to think that the functions of InvertedIndex should be imported too due to the `from InvertedIndex import *` or is this incorrect thinking?

**Comment by WK-GiHu** [comment]
@MTXIII 

>nothing from InvertedIndex is imported.
>Am I correct to think that the functions of InvertedIndex should be imported too due to the `from InvertedIndex import *` or is this incorrect thinking?

The import should look like this:
https://github.com/MTXIII/InvIndex-w-tkinter/blob/28196ab3403385cc8eed6c830c4dcaa237170e44/gui.py#L2

---

>`... import *`

Avoid , `import *` read [importing-from-a-package](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package)

**Comment by MTXIII** [comment]
@WK-GiHu 
Ok, that is how I have been importing. 
I tried `from InvertedIndex import *` to see if that would change things but both are still firing `NameError: name 'bck' is not defined`. 

What other means of troubleshooting can I do to figure out the issue?

**Comment by WK-GiHu** [comment]
@MTXIII 

>What other means of troubleshooting can I do to figure out the issue?

Don't change anything, and make sure you use the versions as shown in **THIS** files:

- [ ] [gui.py](https://github.com/MTXIII/InvIndex-w-tkinter/blob/master/gui.py) file.
  https://github.com/MTXIII/InvIndex-w-tkinter/blob/327109a02d4e1447fbad69668fbe6d5f4ef582a0/gui.py#L3
  https://github.com/MTXIII/InvIndex-w-tkinter/blob/327109a02d4e1447fbad69668fbe6d5f4ef582a0/gui.py#L18
- [ ] [InvertedIndex.py](https://github.com/MTXIII/InvIndex-w-tkinter/blob/master/InvertedIndex.py)
  https://github.com/MTXIII/InvIndex-w-tkinter/blob/327109a02d4e1447fbad69668fbe6d5f4ef582a0/InvertedIndex.py#L127

Repeat the check, and show the output with Traceback: 
```
   print(bck)
   print(dir(bck))
   for line in bck.index_lookup_query(Term.get()):
       ...
```

**Comment by MTXIII** [comment]
@WK-GiHu 
Ok. I've moved them to a new (empty) directory and verified all of those lines are in the files -- I have also updated the files here on github to be current with my files. 

Here is the output of those statements:

```
>>> import  gui
>>> print(bck)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bck' is not defined
>>> print(dir(bck))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bck' is not defined
>>> for line in bck.index_lookup_query(Term.get()):
...           
```

**Comment by MTXIII** [comment]
When I run `python gui.py` directly, enter a term into the search box and click search the traceback is:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MTXIII\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\MTXIII\Documents\Dev\Python\Projects\InvIndex\gui\InvInd\Test\gui.py", line 17, in open
    for line in bck.index_lookup_query(Term.get()):
AttributeError: module 'InvertedIndex' has no attribute 'index_lookup_query'
```

**Comment by WK-GiHu** [comment]
@MTXIII 
 >When I run python gui.py directly,

What is the difference, resulting in your first comment output?
This `pyhton gui.py` is the correct one.

---

### ***Bad, that you **don't** show the check output with your second comment.***
https://github.com/MTXIII/InvIndex-w-tkinter/issues/5#issuecomment-568102641

**Repeat the check**
- [ ] Add these two `print(...` statements, run it using `python gui.py`, and show the output with Traceback: 

Add the `print(...` statements right after this Line
https://github.com/MTXIII/InvIndex-w-tkinter/blob/bc3fc6ce52425a3f7daf898bd05c9efe73221fb7/gui.py#L2
```
   print(bck)
   print(dir(bck))
```

**Comment by MTXIII** [comment]
@WK-GiHu 
I am using Sublime. 
My apologies for not showing the check output.

I believe I've figured out what the issue was. A circular dependancy.
I've removed `import gui as g` from **InvertedIndex.py** and no longer get the `AttributeError`. 
After adding the statements to the file and running **gui.py** the output shows:
```
<module 'InvertedIndex' from 'C:\\Users\\MTXIII\\Documents\\Dev\\Python\\Projects\\InvIndex\\gui\\InvInd\\Test\\InvertedIndex.py'>
['Appearance', 'Database', 'InvertedIndex', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'index_documents', 'index_lookup_query', 'main', 're']
```

As you can see `index_lookup_query` is included, and the program works correctly.

**Comment by MTXIII** [comment]
@WK-GiHu 
Thank you very much for your help with this project!
